INSERT INTO user_data (
    ID,
    Name,
    Email_ID,
    resume_score,
    Timestamp,
    Page_no,
    Predicted_Field,
    User_level,
    Actual_skills,
    Recommended_skills,
    Recommended_courses,
    Sentiment_Score,
    Education_Summary,
    Experience_Summary
  )
VALUES (
    ID:int,
    'Name:varchar',
    'Email_ID:varchar',
    'resume_score:varchar',
    'Timestamp:varchar',
    'Page_no:varchar',
    'Predicted_Field:blob',
    'User_level:blob',
    'Actual_skills:blob',
    'Recommended_skills:blob',
    'Recommended_courses:blob',
    'Sentiment_Score:varchar',
    'Education_Summary:blob',
    'Experience_Summary:blob'
  );